name: Publish

on: workflow_dispatch

jobs:
    build:
        name: Build and Publish
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 8.x

            - name: Install dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --no-restore --configuration Release

            - name: Test
              run: dotnet test --configuration Release

            - name: Pack
              run: dotnet pack --no-build --configuration Release

            - name: Add Nuget source
              run: |
                  dotnet nuget add source --username ${{ secrets.NUGET_USERNAME }} --password ${{ secrets.NUGET_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

            - name: Publish
              run: dotnet nuget push ./Results/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source "github"

            - name: Bump version
              uses: KageKirin/bump-csproj-version@v0
              id: bump_version
              with:
                  file: Results/Results.csproj
                  patch: true

            - name: Commit version
              run: |
                  echo "Bump version to ${{ steps.bump_version.outputs.version }}"
                  git config --local user.email github-actions
                  git config --local user.name github-actions
                  git add Results/Results.csproj
                  git commit -m "Bump version to ${{ steps.bump_version.outputs.version }}"
                  git push
